name: DATA311
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - brotli-python=1.1.0=py311h3e6a449_4
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py311h3485c13_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311h3fd045d_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py311h5dfdfe8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.0.0=h9e37d49_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.6=default_ha2db4b5_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_7
  - libglib=2.84.0=h7025463_0
  - libgomp=15.2.0=h1383e82_7
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - libpng=1.6.51=h7351971_0
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libtiff=4.7.0=hfc51747_1
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.8=h741aa76_1
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.3=hfa2b4ca_0
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.8=py311h1ea47a8_0
  - matplotlib-base=3.10.8=py311h1675fdf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2024.2.2=h57928b3_16
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.3=py311h80b3fa1_0
  - openjpeg=2.5.3=h24db6dd_1
  - openpyxl=3.1.5=py311h4d8bf61_2
  - openssl=3.6.0=h725018a_0
  - outcome=1.3.0.post0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h11fd7f3_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.44=h99c9b8b_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h26a3c52_3
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.1=py311h3485c13_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pymysql=1.1.2=pyhcf101f3_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.0=py311h9f82be6_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.11.13=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py311hefeebc8_1
  - pyzmq=27.1.0=py311hb77b9c8_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.0=h83cda92_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py311h8a15ebc_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - selenium=4.38.0=pyhcf101f3_0
  - selenium-manager=4.38.0=h18a1a76_0
  - setuptools=80.9.0=py311haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h17033d2_1
  - tbb=2021.13.0=h18a62a1_3
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.2=py311h3485c13_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trio=0.32.0=py311h34909f0_1
  - trio-websocket=0.12.2=pyh29332c3_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=17.0.0=py311h3485c13_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webdriver-manager=4.0.2=pyhd8ed1ab_1
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wsproto=1.3.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.25.0=py311hf893f09_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - koreanize-matplotlib==0.1.1
      - scipy==1.16.3
prefix: C:\Users\khw27\anaconda3\envs\DATA311
